In [7]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
df = pd.read_csv(r"C:\MCA_acadamics\Genai_updated\venv\Reviews.csv", nrows=50000)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (50000, 10)


,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


Find Reviews Containing the Word "light"

In [9]:
light_reviews = df[df["Text"].str.contains(r"\blight\b", case=False, na=False)]

print("Number of reviews containing 'light':", len(light_reviews))

light_reviews[["Text"]].head(20)

Number of reviews containing 'light': 1415


,Text
2,This is a confection that has been around a fe...
238,A very delicate green tea with a smooth light ...
269,This is a delicious sugar. It has a pretty lig...
396,Arrowhead Mills Buttermilk Pancake mix is my f...
404,A good tasting light chip that has some value ...
462,Kettle Chips flavors can be hit or miss. Some...
466,"I'm addicted to salty and tangy flavors, so wh..."
467,These Honey Dijon chips bring a terrific balan...
486,Just got this order and it is ok. A bit light ...
556,DEfintely not as tasty as the Madhouse Munchie...


Select Three Sentences

Replace the example sentences below with actual reviews from your dataset that match the required contexts.

In [10]:
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    
    "The packaging was broken and let too much light inside the box.",
    
    "I prefer this brand because it is a light and healthy snack."
]

for i, sentence in enumerate(sentences, start=1):
    print(f"Sentence {i}:")
    print(sentence)
    print()

Sentence 1:
This olive oil is wonderful and very light on the stomach.

Sentence 2:
The packaging was broken and let too much light inside the box.

Sentence 3:
I prefer this brand because it is a light and healthy snack.



Create Bag-of-Words Vectors

In [11]:
vectorizer = CountVectorizer()

dtm = vectorizer.fit_transform(sentences)

dense_matrix = dtm.toarray()

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nDocument-Term Matrix:")
print(dense_matrix)

Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

Document-Term Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


Extract Individual Vectors

In [12]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


: Compute Dot Product Similarities

In [13]:
similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

print("Similarity (Sentence 1 vs Sentence 2):", similarity_1_2)
print("Similarity (Sentence 1 vs Sentence 3):", similarity_1_3)

Similarity (Sentence 1 vs Sentence 2): 4
Similarity (Sentence 1 vs Sentence 3): 4


Show Word Frequencies (Optional Visualization)

In [14]:
feature_names = vectorizer.get_feature_names_out()

vector_df = pd.DataFrame(
    dense_matrix,
    columns=feature_names,
    index=["Sentence_1", "Sentence_2", "Sentence_3"]
)

vector_df

,and,because,box,brand,broken,healthy,inside,is,it,let,...,packaging,prefer,snack,stomach,the,this,too,very,was,wonderful
Sentence_1,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,0,1,0,1
Sentence_2,1,0,1,0,1,0,1,0,0,1,...,1,0,0,0,2,0,1,0,1,0
Sentence_3,1,1,0,1,0,1,0,1,1,0,...,0,1,1,0,0,1,0,0,0,0


conculsion


In [15]:

print("\n===================================")
print("DOT PRODUCT SIMILARITY SCORES")
print("===================================")

print(f"Sentence 1 vs Sentence 2 (Different Contexts): {similarity_1_2}")

print(f"Sentence 1 vs Sentence 3 (Similar Contexts): {similarity_1_3}")

print("\nConclusion:")
if similarity_1_2 > 0:
    print("Bag-of-Words treats both uses of 'light' as mathematically related because it only counts word occurrences.")
else:
    print("No direct overlap detected.")

print("This demonstrates the polysemy problem: the model cannot understand that 'light' has different meanings in different contexts.")


DOT PRODUCT SIMILARITY SCORES
Sentence 1 vs Sentence 2 (Different Contexts): 4
Sentence 1 vs Sentence 3 (Similar Contexts): 4

Conclusion:
Bag-of-Words treats both uses of 'light' as mathematically related because it only counts word occurrences.
This demonstrates the polysemy problem: the model cannot understand that 'light' has different meanings in different contexts.
